pipeline {
    agent { label 'RavindraB12MyLinuxagent' }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Ravindra2409/TravelMemory.git'
            }
        }
        stage('Install') {
            steps {
                sh 'cd backend; npm install'
            }
        }
        stage('Build') {
            steps {
                sh 'cd backend; npm run build'
            }
        }
    }

}


